subscription GetQCWorklist(
  $where: [ngl_task_bool_exp]
  $taskType: String
  $order_by: [ngl_task_order_by!]
  $limit: Int, 
  $offset: Int, 
  $assignee: String!) {
  result: ngl_task(
    where: {
      performing_by: {_eq: $assignee}
      task_type_id: {_eq: $taskType}
      _and: $where
    },
    order_by: $order_by
    limit: $limit, 
    offset: $offset
    ) {
    id
    created_by
    create_date_time
    deadline_at
    document_in_datetime
    external_id
    primary_document {
      document {
        document_number
        document_type {
          code
        }
      }
    }
    application {
      application_date_time_in
      application_id
      accounts {
        sub_product_type_id
      }
      application_group {
        code
      }
      application_type {
        code
      }
      application_channel {
        code
      }
      application_class {
        code
      }
      primary_borrower {
        borrower {
          party_type_id
          party {
            full_name_en
            name
            last_name
            party_juristic_infos {
              juristic_name
            }
          }
        }
      }
      primary_account {
        account {
          product_group {
            code
          }
          product_type {
            code
          }
        }
      }
    }
    indexing_type {
      code
    }
    previous_task {
      task_type {
        code
      }
    }
  }
}
