subscription GetCheckListWorklist(
  $where: [ngl_task_bool_exp]
  $order_by: [ngl_task_order_by!]
  $limit: Int
  $offset: Int
  $assignee: String!
) {
  result: ngl_task(
    where: {
      performing_by: { _eq: $assignee }
      task_type_id: { _eq: "CheckList" }
      _and: $where
    }
    order_by: $order_by
    limit: $limit
    offset: $offset
  ) {
    id
    sla_wb {
      current_duration_minutes
    }
    sla_tty {
      current_duration_minutes
    }
    document_in_datetime
    external_id
    primary_document {
      document {
        document_number
        document_type {
          code
        }

      }
    }
    application {
      application_id
      application_group {
        code
      }
      application_type {
        code
      }
      application_channel {
        code
      }
      application_class {
        code
      }
      primary_borrower {
        borrower {
          party_type_id
          party {
            full_name_en
            name
            last_name
            customer_type_code
          }
        }
      }
      primary_account {
        account {
          product_type {
            code
          }
        }
      }
    }
    indexing_type {
      code
    }
    previous_task {
      task_type {
        code
      }
    }
  }
}